# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 06:02:15 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: ga4gh-report-comparison, revision: 7, authored by: peter.krusche
# https://precision.fda.gov/apps/app-F3197000zGFzq5Yy9yGyzX6F

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Install app-specific Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	python-jinja2

# Download app assets
RUN curl https://dl.dnanex.us/F/D/QvpX09B34fBZYyG3kK3kpfGYgGxpP840yKy8Y6Gj/ga4gh-report-v0.1.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"method_1\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Method\\ 1\\\",\\\"help\\\":\\\"Label\\ for\\ first\\ result\\\",\\\"default\\\":\\\"Method\\ 1\\\"\\},\\{\\\"name\\\":\\\"comparison_method_1\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Comparison\\ method\\ 1\\\",\\\"help\\\":\\\"Comparison\\ method\\ label\\ for\\ first\\ result\\\",\\\"default\\\":\\\"hap.py\\\"\\},\\{\\\"name\\\":\\\"result_1\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"GA4GH\\ comparison\\ app\\ result\\ 1\\\",\\\"help\\\":\\\"output.tar.gz\\ file\\ with\\ full\\ results\\ from\\ hap.py\\ comparison\\\"\\},\\{\\\"name\\\":\\\"method_2\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Method\\ 2\\\",\\\"help\\\":\\\"Label\\ for\\ second\\ result\\\",\\\"default\\\":\\\"Method\\ 2\\\"\\},\\{\\\"name\\\":\\\"comparison_method_2\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Comparison\\ method\\ 2\\\",\\\"help\\\":\\\"Comparison\\ method\\ label\\ for\\ second\\ result\\\",\\\"default\\\":\\\"hap.py\\\"\\},\\{\\\"name\\\":\\\"result_2\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"GA4GH\\ comparison\\ app\\ result\\ 2\\\",\\\"help\\\":\\\"output.tar.gz\\ file\\ with\\ full\\ results\\ from\\ hap.py\\ comparison\\\"\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"report_html\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Comparison\\ report\\\",\\\"help\\\":\\\"The\\ resulting\\ report\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-4\\\"\\},\\\"assets\\\":\\[\\\"file-F319538079Pzq5Yy9yGyzX56\\\"\\],\\\"packages\\\":\\[\\\"python-jinja2\\\"\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"set\\ -e\\\\n\\\\nSAFE_LABEL_1\\=\\$\\(echo\\ \\\\\\\"\\$\\{method_1\\}\\\\\\\"\\ \\|\\ sed\\ -e\\ \\'s/\\[\\^A-Za-z0-9\\\\\\\\.,\\]/-/g\\'\\)\\\\nSAFE_LABEL_M1\\=\\$\\(echo\\ \\\\\\\"\\$\\{comparison_method_1\\}\\\\\\\"\\ \\|\\ sed\\ -e\\ \\'s/\\[\\^A-Za-z0-9\\\\\\\\.,\\]/-/g\\'\\)\\\\nSAFE_LABEL_2\\=\\$\\(echo\\ \\\\\\\"\\$\\{method_2\\}\\\\\\\"\\ \\|\\ sed\\ -e\\ \\'s/\\[\\^A-Za-z0-9\\\\\\\\.,\\]/-/g\\'\\)\\\\nSAFE_LABEL_M2\\=\\$\\(echo\\ \\\\\\\"\\$\\{comparison_method_2\\}\\\\\\\"\\ \\|\\ sed\\ -e\\ \\'s/\\[\\^A-Za-z0-9\\\\\\\\.,\\]/-/g\\'\\)\\\\n\\\\nmkdir\\ -p\\ results_1\\\\ncd\\ results_1\\\\ntar\\ xzvf\\ \\$\\{result_1_path\\}\\\\ncd\\ ..\\\\n\\\\nmkdir\\ -p\\ results_2\\\\ncd\\ results_2\\\\ntar\\ xzvf\\ \\$\\{result_2_path\\}\\\\ncd\\ ..\\\\n\\\\nREPPY_INPUTS\\=\\\\\\\"\\\\\\\"\\\\n\\\\n\\#\\ GA4GH\\ v25\\ app\\ outputs\\ might\\ contain\\ two\\ results\\ each\\\\nfor\\ f\\ in\\ results_1/results/result_1.roc.all.csv.gz\\ \\ results_1/results/result_2.roc.all.csv.gz\\ \\;\\ do\\\\n\\ \\ \\ \\ if\\ \\[\\[\\ -f\\ \\$f\\ \\]\\]\\;\\ then\\\\n\\ \\ \\ \\ \\ \\ \\ \\ REPPY_INPUTS\\=\\\\\\\"\\$\\{REPPY_INPUTS\\}\\ \\$\\{SAFE_LABEL_1\\}_\\$\\{SAFE_LABEL_M1\\}:\\$f\\\\\\\"\\\\n\\ \\ \\ \\ fi\\\\ndone\\\\n\\\\nfor\\ f\\ in\\ results_2/results/result_1.roc.all.csv.gz\\ \\ results_2/results/result_2.roc.all.csv.gz\\ \\;\\ do\\\\n\\ \\ \\ \\ if\\ \\[\\[\\ -f\\ \\$f\\ \\]\\]\\;\\ then\\\\n\\ \\ \\ \\ \\ \\ \\ \\ REPPY_INPUTS\\=\\\\\\\"\\$\\{REPPY_INPUTS\\}\\ \\$\\{SAFE_LABEL_2\\}_\\$\\{SAFE_LABEL_M2\\}:\\$f\\\\\\\"\\\\n\\ \\ \\ \\ fi\\\\ndone\\\\n\\\\nREPPY\\=\\\\\\\"python\\ /opt/ga4gh-reporting/bin/rep.py\\ \\$REPPY_INPUTS\\ -o\\ comparison.html\\\\\\\"\\\\necho\\ \\\\\\\"\\$REPPY\\\\\\\"\\\\n\\$REPPY\\\\n\\\\nemit\\ report_html\\ comparison.html\\\\n\\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work